allocation_map:
  bond:
    allocation: 10
    symbols:
    - currency: ''
      symbol: ''
    buy: ''
  cad_etf:
    allocation: 30
    symbols:
    - currency: ''
      symbol: ''
    buy: ''
  ex_ca_etf:
    allocation: 20
    symbols:
    - currency: ''
      symbol: ''
    buy: ''
  global_etf:
    allocation: 10
    symbols:
    - currency: ''
      symbol: ''
    buy: ''
  ind_stocks:
    allocation: 5
    symbols:
    - currency: ''
      symbol: ''
    buy: ''
  na_etf:
    allocation: 25
    symbols:
    - currency: ''
      symbol: ''
    buy: ''
auth:
  questrade:
    refresh_token: your_refresh_token_here
  google:
    client_id: id_here
    client_secret: secret_here
    refresh_token: refresh_token_here
mail:
  source_account: ___@gmail.com
  dest_account: ___@gmail.com
  
  